### ISSUE TITLE
Fix the SW on Saturn's demo page

### ISSUE THREAD

**Issue by reidlw** [filecoin-saturn/saturn-demo#4]
"deploy this repo to github pages and ensure the SW is working while not being under root directory because of the way github pages get addressed (github.pages/{repo}/sw.js )
https://github.com/filecoin-saturn/saturn-demo"

**Comment by joaosa** [comment]
@prodalex What am I actually supposed to deploy here (I suppose it's https://github.com/filecoin-saturn/saturn-demo)? And where (I suppose that's up to me)? :)

**Comment by joaosa** [comment]
Followed [these instructions](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)

"I ended up adding a custom domain to gh pages to fix the path issue. We're now serving the demo under demo.strn.network. http://demo.strn.network/saturn-sw.js is now reachable as a path and it seems to be loading with no errors on Firefox. I can confirm the service worker is registering there.
You can check https://demo.strn.network/"
